-- create_tables.sql
CREATE DATABASE IF NOT EXISTS tableStudent CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE tableStudent;

-- students
CREATE TABLE IF NOT EXISTS students (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fullname VARCHAR(255) NOT NULL,
  matricule VARCHAR(100) NOT NULL,
  group_id VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- attendance: one row per student per session (session 1..6)
CREATE TABLE IF NOT EXISTS attendance (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT NOT NULL,
  session TINYINT NOT NULL,
  present TINYINT NOT NULL DEFAULT 0,
  participated TINYINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY (student_id, session),
  FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
);

-- admins
CREATE TABLE IF NOT EXISTS admins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- insert default admin (username: admin, password: admin123)
INSERT IGNORE INTO admins (username, password_hash) VALUES
('admin', '$2y$10$2r1Frl3u0Xv4x3e2ez6JPe6C2fQ1eB3XpqQ7hXgH9d6qzWoxz7m7e');
-- The above hash = password "admin123" generated by password_hash('admin123', PASSWORD_DEFAULT)
